# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19d046c0077d5fdc794b1d3abe90ac1c09f7a02cf9de6c7e52b0d4fae108cbf64173b6eb49d08e452e39e8a0b889e30a5233778ade4d732687cadf4bc635f4b1

test:
  secret_key_base: 5938f6d2ee8e2e396c71f33cde36aad31de2a0da3dd218f0061e0833b3fa58881b0252953225f73bfd981d348964f47f9c43b8133569ca4747ba79d197b83126

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
